### ISSUE TITLE
Crash dcl_ui_background

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/godot-explorer#73]
https://github.com/decentraland/godot-explorer/blob/76056d2d9a5f0b213214e93e3141a28713135ea1/rust/decentraland-godot-lib/src/godot_classes/dcl_ui_background.rs#L273-L281

```
2023-11-06T22:25:49.795132Z ERROR panic: thread '<unnamed>' panicked at 'failed to convert from variant Variant(ty=Object, val=<RefCounted#-9223369565554053016>) to bool; BadType': /home/kuruk/.cargo/git/checkouts/gdext-76630c89719e160c/00ba8c9/godot-core/src/builtin/variant/variant_traits.rs:20
   0: <backtrace::capture::Backtrace as core::default::Default>::default
             at /home/kuruk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/capture.rs:410:9
   1: log_panics::Config::install_panic_hook::{{closure}}
             at /home/kuruk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/log-panics-2.1.0/src/lib.rs:115:29
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:2007:9
      std::panicking::rust_panic_with_hook
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:709:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:597:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:151:18
   5: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   6: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   7: godot_core::builtin::variant::variant_traits::FromVariant::from_variant::{{closure}}
             at /home/kuruk/.cargo/git/checkouts/gdext-76630c89719e160c/00ba8c9/godot-core/src/builtin/variant/variant_traits.rs:20:13
   8: core::result::Result<T,E>::unwrap_or_else
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/result.rs:1428:23
   9: godot_core::builtin::variant::variant_traits::FromVariant::from_variant
             at /home/kuruk/.cargo/git/checkouts/gdext-76630c89719e160c/00ba8c9/godot-core/src/builtin/variant/variant_traits.rs:19:9
  10: godot_core::builtin::variant::Variant::to
             at /home/kuruk/.cargo/git/checkouts/gdext-76630c89719e160c/00ba8c9/godot-core/src/builtin/variant/mod.rs:46:9
  11: decentraland_godot_lib::godot_classes::dcl_ui_background::DclUiBackground::change_value
             at /home/kuruk/decentraland/godot-explorer/rust/decentraland-godot-lib/src/godot_classes/dcl_ui_background.rs:273:49
  12: decentraland_godot_lib::scene_runner::components::ui::ui_background::update_ui_background
             at /home/kuruk/decentraland/godot-explorer/rust/decentraland-godot-lib/src/scene_runner/components/ui/ui_background.rs:66:13
  13: decentraland_godot_lib::scene_runner::components::ui::scene_ui::update_scene_ui
             at /home/kuruk/decentraland/godot-explorer/rust/decentraland-godot-lib/src/scene_runner/components/ui/scene_ui.rs:252:9
  14: decentraland_godot_lib::scene_runner::update_scene::_process_scene
             at /home/kuruk/decentraland/godot-explorer/rust/decentraland-godot-lib/src/scene_runner/update_scene.rs:170:17
  15: decentraland_godot_lib::scene_runner::scene_manager::SceneManager::scene_runner_update
             at /home/kuruk/decentraland/godot-explorer/rust/decentraland-godot-lib/src/scene_runner/scene_manager.rs:297:20
  16: <decentraland_godot_lib::scene_runner::scene_manager::SceneManager as godot_core::gen::classes::node::re_export::NodeVirtual>::process
             at /home/kuruk/decentraland/godot-explorer/rust/decentraland-godot-lib/src/scene_runner/scene_manager.rs:611:9
  17: <decentraland_godot_lib::scene_runner::scene_manager::SceneManager as godot_core::obj::traits::cap::ImplementsGodotVirtual>::__virtual_call::function::{{closure}}
             at /home/kuruk/decentraland/godot-explorer/rust/decentraland-godot-lib/src/scene_runner/scene_manager.rs:569:1
  18: core::ops::function::FnOnce::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/ops/function.rs:250:5
  19: <(R,P0) as godot_core::builtin::meta::signature::PtrcallSignatureTuple>::ptrcall
             at /home/kuruk/.cargo/git/checkouts/gdext-76630c89719e160c/00ba8c9/godot-core/src/builtin/meta/signature.rs:156:38
  20: <decentraland_godot_lib::scene_runner::scene_manager::SceneManager as godot_core::obj::traits::cap::ImplementsGodotVirtual>::__virtual_call::function
             at /home/kuruk/decentraland/godot-explorer/rust/decentraland-godot-lib/src/scene_runner/scene_manager.rs:569:1
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  29: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  30: <unknown>
```

**Comment by kuruk-mm** [comment]
Fix at https://github.com/decentraland/godot-explorer/pull/79
