### ISSUE TITLE
WebSocket in a Scene panics

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/godot-explorer#97]
Looks like the following code:

https://github.com/decentraland/godot-explorer/blob/39e788f3257431aafdefd97544358479a522b3fd/rust/decentraland-godot-lib/src/dcl/js/websocket/mod.rs#L184-L188

It's panicking with the following message:

```
2023-11-17T00:33:40.906374Z ERROR panic: thread 'scene thread 1' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime': src/dcl/js/websocket/mod.rs:184
   0: <backtrace::capture::Backtrace as core::default::Default>::default
             at /home/kuruk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/capture.rs:410:9
   1: log_panics::Config::install_panic_hook::{{closure}}
             at /home/kuruk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/log-panics-2.1.0/src/lib.rs:115:29
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:2007:9
      std::panicking::rust_panic_with_hook
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:709:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:597:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:151:18
   5: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   6: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   7: core::panicking::panic_display
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:150:5
   8: tokio::task::spawn::spawn_inner
             at /home/kuruk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/spawn.rs:203:23
   9: tokio::task::spawn::spawn
             at /home/kuruk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/spawn.rs:172:13
  10: decentraland_godot_lib::dcl::js::websocket::op_ws_create::call
             at /home/kuruk/decentraland/godot-explorer/rust/decentraland-godot-lib/src/dcl/js/websocket/mod.rs:184:5
  11: decentraland_godot_lib::dcl::js::websocket::op_ws_create::v8_func
             at /home/kuruk/decentraland/godot-explorer/rust/decentraland-godot-lib/src/dcl/js/websocket/mod.rs:158:1
  12: decentraland_godot_lib::dcl::js::websocket::op_ws_create::v8_fn_ptr
             at /home/kuruk/decentraland/godot-explorer/rust/decentraland-godot-lib/src/dcl/js/websocket/mod.rs:158:1
  13: Builtins_CallApiCallbackGeneric
```

# Repro steps:
1. /changerealm https://peer.decentraland.org
2. /goto -9,136

**Comment by kuruk-mm** [comment]
Fixed by https://github.com/decentraland/godot-explorer/pull/326
